# 딥러닝을 이용한 자연어 처리

1. 텍스트의 토큰화

In [ ]:
# ----------------------------------------
# 텍스트(문장)를 숫자로 바꾸기 위해 필요한 도구들 불러오기
# ----------------------------------------

# 문장을 단어 → 숫자로 바꿔주는 도구
from tensorflow.keras.preprocessing.text import Tokenizer
# 문장 길이를 똑같이 맞춰주는 도구 (짧은 문장에 0을 채움)
from tensorflow.keras.preprocessing.sequence import pad_sequences
# 딥러닝 모델의 기본 틀 (층을 차곡차곡 쌓는 상자)
from tensorflow.keras.models import Sequential
# 신경망에서 사용하는 층들
from tensorflow.keras.layers import Dense,Flatten,Embedding
# 정답(label)을 원-핫(one-hot) 형식으로 바꿔주는 도구
from tensorflow.keras.utils import to_categorical
# 숫자 배열을 다루기 위한 라이브러리
from numpy import array
# 문장을 단어 단위로 쪼개는 함수
from tensorflow.keras.preprocessing.text import text_to_word_sequence

# ----------------------------------------
# 분석할 문장(텍스트) 입력
# ----------------------------------------
text='해보지 않으면 해낼 수 없다'
# → 우리가 컴퓨터에게 이해시키고 싶은 문장


# ----------------------------------------
# 문장을 단어 단위로 나누기 (토큰화)
# ----------------------------------------
result=text_to_word_sequence(text)


# text_to_word_sequence가 하는 일:
# "해보지 않으면 해낼 수 없다"
# → ['해보지', '않으면', '해낼', '수', '없다']
# 즉, 문장을 단어 리스트로 바꿔줌


# ----------------------------------------
# 결과 출력
# ----------------------------------------

# 원래 문장 출력
print("\n원문:\n",text)
# 단어로 쪼갠 결과 출력
print("\n토큰화\n",result)

C:\Users\User\AppData\Roaming\Python\Python313\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):



원문:
 해보지 않으면 해낼 수 없다

토큰화
 ['해보지', '않으면', '해낼', '수', '없다']


In [ ]:
# -----------------------------------------
# 1️⃣ 분석할 문장(텍스트) 3개를 준비
# -----------------------------------------
# 컴퓨터에게 읽게 할 문장들

docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
'텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
'토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',
]

# -----------------------------------------
# 2️⃣ Tokenizer 생성
# -----------------------------------------
# Tokenizer는
# "문장을 읽고 → 단어를 쪼개고 → 단어를 세고 → 번호를 붙이는" 도구

token=Tokenizer()

# -----------------------------------------
# 3️⃣ 문장 분석 시작
# -----------------------------------------
# docs 안에 있는 모든 문장을 읽어서
# - 단어를 분리하고
# - 단어가 몇 번 나왔는지 세고
# - 각 단어에 고유 번호(인덱스)를 부여함
token.fit_on_texts(docs)


# -----------------------------------------
# 4️⃣ 단어 빈도수 출력
# -----------------------------------------
# word_counts는
# "각 단어가 전체 문장에서 몇 번 나왔는지"를 보여줌
# (Bag-of-Words의 핵심 정보)
print("\n단어 카운트:\n",token.word_counts)

# -----------------------------------------
# 5️⃣ 문장 개수 출력
# -----------------------------------------
# 우리가 입력한 문장이 몇 개인지 알려줌
print("\n문장  카운트:",token.document_count)

# -----------------------------------------
# 6️⃣ 각 단어가 몇 개의 문장에 등장했는지
# -----------------------------------------
# 예를 들어 "토큰화"가 3이라면
# → 3개의 문장 모두에 그 단어가 들어있다는 뜻
print("\n각 단어가 몇개의 문장에 포함되어 있는가: \n",token.word_docs)


# -----------------------------------------
# 7️⃣ 단어에 매겨진 번호(인덱스)
# -----------------------------------------
# 컴퓨터는 글자를 직접 처리하지 못하므로
# 모든 단어에 숫자를 붙여서 사용함
# 예: 토큰화 → 1, 딥러닝 → 2 같은 식
print("\n각 단어에 매겨진 인덱스 값:\n",token.word_index)


단어 카운트:
 OrderedDict({'먼저': 1, '텍스트의': 2, '각': 1, '단어를': 1, '나누어': 1, '토큰화합니다': 1, '단어로': 1, '토큰화해야': 1, '딥러닝에서': 2, '인식됩니다': 1, '토큰화한': 1, '결과는': 1, '사용할': 1, '수': 1, '있습니다': 1})

문장  카운트: 3

각 단어가 몇개의 문장에 포함되어 있는가: 
 defaultdict(<class 'int'>, {'토큰화합니다': 1, '각': 1, '단어를': 1, '먼저': 1, '텍스트의': 2, '나누어': 1, '토큰화해야': 1, '인식됩니다': 1, '딥러닝에서': 2, '단어로': 1, '사용할': 1, '수': 1, '토큰화한': 1, '있습니다': 1, '결과는': 1})

각 단어에 매겨진 인덱스 값:
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토큰화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


## 단어의 원-핫 인코딩

In [ ]:
# -----------------------------------------
# 1️⃣ 분석할 문장(텍스트) 준비
# -----------------------------------------
text="오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"
# → 우리가 컴퓨터에게 이해시키고 싶은 문장


# -----------------------------------------
# 2️⃣ Tokenizer 생성
# -----------------------------------------
# Tokenizer는
# "단어를 나누고 → 번호를 붙이고 → 숫자로 바꿔주는" 도구
token=Tokenizer()

# -----------------------------------------
# 3️⃣ 문장을 Tokenizer에게 학습시키기
# -----------------------------------------
# [text] 처럼 리스트로 넣는 이유는
# 여러 문장을 처리할 수 있게 하기 위함
token.fit_on_texts([text])

# 이 과정에서 Tokenizer는 내부적으로
# 오랫동안 → 1
# 꿈꾸는   → 2
# 이는     → 3
# 그       → 4
# 꿈을     → 5
# 닮아간다 → 6
# 처럼 단어에 숫자를 붙임


# -----------------------------------------
# 4️⃣ 단어 → 숫자 사전 확인
# -----------------------------------------
# 어떤 단어가 어떤 숫자로 바뀌었는지 출력
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [ ]:
# -----------------------------------------
# 5️⃣ 문장을 숫자 시퀀스로 변환
# -----------------------------------------
# 문장을 단어 번호로 바꿈
# "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"
# → [1, 2, 3, 4, 5, 6]
x=token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [ ]:
# -----------------------------------------
# 6️⃣ 전체 단어 개수 계산
# -----------------------------------------
# 단어 개수 = 6개
# 딥러닝에서는 0번도 쓰기 때문에 +1 해줌
word_size=len(token.word_index)+1

# -----------------------------------------
# 7️⃣ 원-핫 인코딩 (One-Hot Encoding)
# -----------------------------------------
# 각 숫자를 벡터(0과 1로 된 배열)로 바꿈
# 예:
# 1 → [0,1,0,0,0,0,0]
# 2 → [0,0,1,0,0,0,0]
# ...
x=to_categorical(x,num_classes=word_size)

# 최종적으로 x는
# "문장 전체를 숫자 벡터들의 모음"으로 바꾼 결과가 됨
print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


이 질문이 **진짜 핵심**이야 👍
둘은 완전히 다른 일을 해.

---

## 1️⃣ `print(token.word_index)`

이건 **사전(dictionary)**을 보여주는 거야.

```python
{'오랫동안':1, '꿈꾸는':2, '이는':3, '그':4, '꿈을':5, '닮아간다':6}
```

의미는:

> "각 단어에 어떤 번호를 붙였는지 알려주는 표"

즉,
📖 **단어 → 번호 매핑표**

이건 **변환 결과가 아니라 규칙**이야.

---

## 2️⃣ `token.texts_to_sequences([text])`

이건 **그 규칙을 실제 문장에 적용하는 것**

문장:

```
오랫동안 꿈꾸는 이는 그 꿈을 닮아간다
```

→ 단어 하나씩 바꾼다:

```
오랫동안 → 1  
꿈꾸는   → 2  
이는     → 3  
그       → 4  
꿈을     → 5  
닮아간다 → 6
```

결과:

```
[[1, 2, 3, 4, 5, 6]]
```

---

## 🔥 핵심 차이

| 코드                     | 하는 일                   |
| ---------------------- | ---------------------- |
| `token.word_index`     | **단어-번호 사전** (규칙표)     |
| `texts_to_sequences()` | **그 규칙으로 문장을 숫자로 바꾸기** |

---

## 🧠 비유로 이해하기

### `word_index`

= 영어 사전

```
apple → 1
banana → 2
```

### `texts_to_sequences`

= 영어 문장을 숫자로 번역

```
"I like apple"
→ [?, ?, 1]
```

---

## 🎯 한 줄 요약

> `word_index`는 **“단어 사전”**,
> `texts_to_sequences`는 **“그 사전으로 문장을 숫자로 바꾸는 것”**이다.

이 차이를 알면 NLP 전체 흐름이 이해된다 😄


이건 진짜 많은 사람들이 헷갈리는 부분이야.
핵심을 **아주 직관적으로** 설명해줄게.

---

## 🎯 결론부터 말하면

> **쓸데없이 늘어난 게 아니라
> “0번 자리”를 비워두는 안전 공간이 하나 있는 것**이야.

---

## 🧸 장난감 상자 비유

단어가 6개라서
우리가 이렇게 번호를 붙였다고 해보자:

```
1번: 오랫동안  
2번: 꿈꾸는  
3번: 이는  
4번: 그  
5번: 꿈을  
6번: 닮아간다
```

그럼 너는
**6칸짜리 상자**를 만들고 싶겠지?

하지만 컴퓨터는 상자를 이렇게 센다:

```
0번, 1번, 2번, 3번, 4번, 5번, 6번
```

👉 이미 7칸이야 😅

컴퓨터는 **0부터 시작**하기 때문에
1번 상자를 쓰려면
0번 상자도 같이 만들어야 한다.

---

## 🧠 0번 상자는 뭐냐?

0번은 보통 이런 뜻으로 쓰인다:

* "아무 단어도 없음"
* "패딩"
* "빈칸"

예:

```
[0, 0, 0, 3, 5]
```

→ 앞의 0들은 "비어 있는 자리"

이게 없으면
문장 길이 맞추기가 불가능해짐.

---

## 🔥 그래서 진짜 이유는 이것

> **원-핫의 1칸은
> “비어 있음(Padding, 없음)”을 표현하기 위해 존재한다**

즉,

| 번호  | 의미        |
| --- | --------- |
| 0   | 아무 단어도 없음 |
| 1~6 | 실제 단어들    |

그래서 단어는 6개인데
**원-핫은 7칸이 필요한 것**

---

## 🧠 한 줄 요약

> **+1은 낭비가 아니라
> “빈칸(아무 단어도 없음)”을 표현하기 위한 자리다.**

이게 없으면 딥러닝에서 문장을 다룰 수 없어 😄


In [ ]:
# -----------------------------------------
# 1️⃣ 영화 리뷰 문장들 (입력 데이터)
# -----------------------------------------
# 사람이 쓴 영화 리뷰 10개
# 앞의 5개는 좋은 리뷰, 뒤의 5개는 나쁜 리뷰
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다",
"한번 더 보고싶네요","글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

# -----------------------------------------
# 2️⃣ 정답(label) 만들기
# -----------------------------------------
# 각 문장이 좋은 리뷰인지(1) 나쁜 리뷰인지(0)를 표시
# docs와 순서가 1:1로 대응됨
classes=array([1,1,1,1,1,0,0,0,0,0])


# -----------------------------------------
# 3️⃣ Tokenizer 생성
# -----------------------------------------
# Tokenizer는
# "문장을 단어로 나누고 → 단어에 번호를 붙이는 도구"
token=Tokenizer()


# -----------------------------------------
# 4️⃣ 모든 리뷰 문장을 Tokenizer에게 학습시키기
# -----------------------------------------
# docs 안의 모든 문장을 읽으면서
# - 단어를 쪼개고
# - 같은 단어를 모으고
# - 단어마다 숫자 번호를 붙임
token.fit_on_texts(docs)


# -----------------------------------------
# 5️⃣ 단어 사전 출력
# -----------------------------------------
# 어떤 단어가 어떤 번호를 받았는지 확인
# 예: "영화예요" → 1, "너무" → 2 같은 식
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}


In [ ]:
# -----------------------------------------
# 1️⃣ 리뷰 문장들을 숫자(토큰)로 변환
# -----------------------------------------
# token.word_index 에 있는
# "단어 → 숫자" 사전을 이용해서
# docs에 있는 각 문장을 숫자 배열로 바꾼다.
# 예: "너무 재밌네요" → [1, 2]

x=token.texts_to_sequences(docs)


# -----------------------------------------
# 2️⃣ 토큰화된 결과 출력
# -----------------------------------------
# 각 리뷰 문장이 어떤 숫자들로 바뀌었는지 확인
print("\n리뷰 텍스트,토큰화 결과:\n",x)


리뷰 텍스트,토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [ ]:
# -----------------------------------------
# 3️⃣ 패딩(Padding)으로 길이 맞추기
# -----------------------------------------
# 딥러닝 모델은 모든 입력의 길이가 같아야 한다.
# 그런데 리뷰 문장마다 단어 개수가 다르기 때문에
# 길이를 4로 통일시켜야 함.
# 짧은 문장 앞에 0을 채워서 길이를 4로 맞춘다.

padded_x=pad_sequences(x,4)


# -----------------------------------------
# 4️⃣ 패딩 결과 출력
# -----------------------------------------
# 이제 모든 리뷰가 길이 4짜리 숫자 배열이 되었음
print("\n패딩 결과:\n",padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


| 부분     | 뜻                           |
| ------ | --------------------------- |
| `None` | 한 번에 몇 문장이 들어올지는 몰라 (배치 크기) |
| `4`    | **한 문장은 숫자 4개로 들어온다**       |


In [ ]:
# -----------------------------------------
# 1️⃣ 전체 단어 개수 계산
# -----------------------------------------
# token.word_index에는
# "단어 → 숫자" 사전이 들어 있음
# 여기에 0번(빈칸, 패딩용)을 포함해야 하므로 +1
word_size=len(token.word_index)+1


# -----------------------------------------
# 2️⃣ 신경망(모델) 틀 만들기
# -----------------------------------------
# Sequential은
# 층을 위에서부터 차례대로 쌓는 신경망
model=Sequential()

# -----------------------------------------
# 3️⃣ Embedding 층
# -----------------------------------------
# 이 층은
# "단어 번호 → 의미를 가진 숫자 벡터"로 바꿔줌
# word_size: 사용할 단어 개수 (0번 포함)
# 8: 각 단어를 8개의 숫자로 표현하겠다는 뜻
model.add(Embedding(word_size,8))

# -----------------------------------------
# 4️⃣ Flatten 층
# -----------------------------------------
# Embedding 결과는 2차원 배열(단어 개수 × 8)
# 이를 1차원으로 쭉 펴서
# Dense 층이 처리할 수 있게 만듦
model.add(Flatten())


# -----------------------------------------
# 5️⃣ 출력층 (분류기)
# -----------------------------------------
# Dense(1) → 결과를 숫자 하나로 출력
# sigmoid → 0~1 사이 값으로 변환
# 1에 가까우면 '좋은 리뷰'
# 0에 가까우면 '나쁜 리뷰'
model.add(Dense(1,activation='sigmoid'))

# -----------------------------------------
# 6️⃣ 입력 형태 지정
# -----------------------------------------
# 이 모델은
# "단어 4개짜리 문장"을 입력으로 받음
# None → 한 번에 몇 문장이 들어올지는 몰라도 됨

model.build(input_shape=(None,4))

# -----------------------------------------
# 7️⃣ 모델 구조 출력
# -----------------------------------------
# 모델이 어떤 층으로 구성되어 있는지 확인
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 4, 8)           │           168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 201 (804.00 B)

 Trainable params: 201 (804.00 B)

 Non-trainable params: 0 (0.00 B)

https://chatgpt.com/share/6964adc3-7f44-800e-b554-e2d24b142204

In [ ]:
# -----------------------------------------
# 1️⃣ 모델 학습 방법 설정
# -----------------------------------------
# 이 모델에게
# "어떻게 공부할지"를 알려주는 단계

# optimizer='adam'
# → 틀린 답을 얼마나, 어떻게 고칠지 정하는 방법
# → Adam은 자동으로 학습 속도를 조절해 주는 똑똑한 방식

# loss='binary_crossentropy'
# → 지금 문제는 "좋다(1) / 나쁘다(0)" 두 가지 중 하나를 고르는 문제
# → 그래서 이진 분류 전용 오차 함수 사용

# metrics=['accuracy']
# → 학습 중에 맞춘 비율(정확도)을 같이 보여달라는 뜻

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


# -----------------------------------------
# 2️⃣ 모델 학습 시작
# -----------------------------------------
# padded_x → 리뷰 문장(숫자로 변환된 입력 데이터)
# classes  → 각 리뷰의 정답(1: 좋음, 0: 나쁨)
# epochs=20 → 전체 데이터를 20번 반복해서 학습
model.fit(padded_x,classes,epochs=20)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 477ms/step - accuracy: 0.4000 - loss: 0.7026
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.4000 - loss: 0.6996
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.4000 - loss: 0.6967
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6937
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6908
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.6879
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6000 - loss: 0.6850
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.7000 - loss: 0.6822
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8000 - loss: 0.6793
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.7000 - loss: 0.6765
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.9000 - loss: 0.6737
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.9000 - loss: 0.6709


In [ ]:
# -----------------------------------------
# 3️⃣ 학습 결과 평가
# -----------------------------------------
# model.evaluate는
# [loss, accuracy] 형태로 결과를 돌려줌

# [1]은 accuracy(정확도)만 가져오는 것
# %.4f → 소수점 네 자리까지 출력
print("\nAccuracy: %.4f" % (model.evaluate(padded_x,classes)[1]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.9000 - loss: 0.6460

Accuracy: 0.9000


: 